export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_SELECTED_PLAN = 'SET_SELECTED_PLAN';
export const PUSH_PLAN = 'PUSH_PLAN';
export const TAKE_PLAN_FROM_LIST = 'TAKE_PLAN_FROM_LIST';
export const REMOVE_SELECTED_PLAN = 'REMOVE_SELECTED_PLAN';
export const CLOSE_PLAN = 'CLOSE_PLAN';
export const SET_WINNER = 'SET_WINNER';

export const ADD_USER_VOTE = 'ADD_USER_VOTE';
export const CONFIRM_VOTE = 'CONFIRM_VOTE';
export const UNCONFIRM_VOTE = 'UNCONFIRM_VOTE';

export const ADD_INVITATION = 'ADD_INVITATION';
export const DISMISS_INVITATION = 'DISMISS_INVITATION';
export const ERASE_INVITATION = 'ERASE_INVITATION';
